<?php $root_dir = $_SERVER["DOCUMENT_ROOT"];

require($root_dir . '/classes/Database.php');

function render_terms_of_service() { ?>

<style type="text/css" media="screen">
	body {
	background-color: #b2dfdb;
}
</style>

<center>
	<div class="white container z-depth-5" style=" margin: 20px 0 20px 0; padding: 40px;">
		<div style="padding: 0 60px 20px 60px;">
			<h3 style="margin-bottom: 40px">Terms of Service</h3>
			<p>Do, Inc. (“<b>Do</b>”) maintains this website and its mobile applications (collectively, the “ <b>Do Site</b>”) as a service to: its visitors; its clients who create websites (“<b>Client Websites</b>”) using Do services (“<b>Services</b>”) through a separate Services Agreement (“<b>Clients</b>”); and visitors to Client’s Websites, (visitors, Clients, and visitors to Client’s Websites are collectively referred to as, the “<b>Users</b>" and individually as “<b>Users</b>").</p>
			<p>Please review the following terms and conditions carefully. This Terms of Use Agreement (the “<b>Term of Use</b>”) is a legally binding contract between each User and Do regarding User’s access to and use of the Do Site and Client’s Websites (collectively, the “<b>Sites</b>”) and any use by User of the Services. By accessing the Sites or Services, the User agrees to these Terms of Use. If a User does not agree with any part of the following Terms of Use, User must not use the Sites or Services.</p>

			<b style="margin-left: 5%;">1. Registration, Accounts, Passwords and Use.</b>
			<p>The Services or Do Site may require registration. Should a User choose to register for such Services, User agrees to provide accurate and current information as required by the relevant registration process, and to promptly update such information as necessary to ensure that it is kept accurate and complete. Further, User agrees to notify Do of any unauthorized use of User’s password or account. The Sites and Services are intended for use by individuals 13 years of age or older. If User is under 18, User may use the Site only with involvement of a parent or legal guardian who agrees to be bound by these Terms of Use.</p>

			<b style="margin-left: 5%;">2. Additional Terms</b>
			<p>Some of Do’s Services have additional terms and conditions (“Additional Terms”). Where Additional Terms apply to a Service, Do will make them available for User to read through prior to User’s use of that Service. By using such Services, User agrees to the applicable Additional Terms.</p>
			<b style="margin-left: 5%;">3. Ownership.</b>
			<p>Except for User Content, the Do Site is the property of Do, its licensors and/or its various third party providers and distributors. The Do Site is protected by copyright, trademark and other intellectual property laws. User must retain all copyright and trademark notices, including any other proprietary notices, contained in the materials, and User agrees not to alter, obscure or obliterate any of such notices. Unless otherwise set forth in these Terms of Use, none of the content or data found in the Do Site may be copied, reproduced, republished, sold, transferred, modified or distributed in any way without the prior written consent of Do, its licensors and/or its third party providers and distributors. Trademarks, logos, images and service marks displayed on the Do Site are the property of either Do or other third parties. Users agree not to display or use any Do or third party marks without prior written consent of Do or the appropriate third party licensor. Do reserves all rights not expressly granted to User.</p>
			<b style="margin-left: 5%;">4. Privacy.</b>
			<p>For information on how User information is collected, used and disclosed by Do, please consult the Privacy Policy.</p>
			<b style="margin-left: 5%;">5. Change of Terms of Use.</b>
			<p>From time to time Do may revise or modify these Terms of Use by posting the revised Terms of Use through a link on the Do Site. Those changes will go into effect on the “Last Updated” date shown in the revised Terms of Use. By continuing to access or use the Site or Services, User agrees to the revised Terms. If User does not agree to any of the Terms of Use set forth herein, User may not use the Sites and Services.</p>
			<b style="margin-left: 5%;">6. User Content.</b>
			<p>The Do Site may allow Users to post or send information, text, data, photographs, audio, video, images, graphics, logos, trademarks, service marks, and other materials (collectively “ User Content”) to or through the Sites. User understands that all of the User Content and the consequences of such posting User Content is User’s sole responsibility and is subject to the Terms of Use and the Do Privacy Policy.</p>
			<p>User understands that by accessing the Sites or Services, User may be exposed to User Content that may be offensive or objectionable to User. Do may, but is not obligated to, preview or review any User Content and, in its sole discretion, may block or may remove from the Sites, without notice, any User Content that violates the Terms of Use or is otherwise objectionable. However, failure to block or remove any User Content is not an endorsement, warranty, representation, or guarantee regarding such User Content.
			User represents and warrants that the User Content does not infringe the copyright, trademark, publicity/privacy right or other intellectual property or proprietary right of any third party and that User has paid and will pay in full any fees or other payments that may be related to the use of User’s User Content.</p>
			<p>By posting, uploading or otherwise distributing the User Content on the Do Site, User hereby grants (and represent and warrant that User has all necessary rights to grant) to Do a perpetual, sublicenseable, transferable, world-wide, non-exclusive, royalty free, fully paid license to all User’s rights in the User Content (including moral rights) for all purposes, including but not limited to use, copy, reproduce, modify, adapt, publish, edit, translate, create derivative works from, transmit, distribute, display, perform, or derive revenue or other remuneration from such User Content and incorporate such User Content into other works in any form, media or technology.</p>
			<p>By providing User Content to the Sites or Services, User hereby permits Do to identify User as the provider of such User Content in any form, media and technology.
			User agrees that Do has no liability or responsibility for the storage or deletion of any User Content that User submits or posts through the Sites or Services.</p>
			<b style="margin-left: 5%;">7. Rules and Conduct.</b>
			<p>Any information; ideas or opinions posted by Users of the Service or Do Site does not necessarily reflect Do’s views. Do does not assume responsibility for the accuracy of any information, ideas or opinions posted by Users and are not liable for any claims, damages or losses resulting from such information, ideas or opinions. When posting any information, materials or content or otherwise accessing the Sites or Services, User agrees that User will not:
			Harass, defame, intimidate or threaten another user;</p>
			<p>Interfere with another user’s rights to privacy;</p>
			<p>Post any material that is defamatory (i.e., disparaging to the reputation of an individual or business);</p>
			<p>Post any material that is obscene, offensive or indecent;</p>
			<p>Post any trademarks, logos, copyrighted material or other intellectual property without the authorization of the owner;
			Operate, conduct, or promote, directly or indirectly, raffles, lotteries or other similar gaming activities, whether for charitable purposes or otherwise;</p>
			<p>Post any materials that may damage the operation of a computer (such as a virus, worm or Trojan horse);</p>
			<p>Use any means to “scrape,” “crawl,” or “spider” any web pages contained in the Sites (although Do does allow operators of public search engines to use spiders to index materials from the Site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials, and Do reserves the right to revoke these exceptions either generally or in specific cases);
			Recruit or otherwise solicit any User to join third party services or websites that are competitive to Do, without Do’s prior written approval;</p>
			<p>Use, display, mirror, or frame the Sites or any individual element within the Sites or Services, Do’s name, any Do trademark, logo, or other proprietary information, or the layout and design of any page or form contained on a page, without Do’s express written consent;</p>
			<p>Access, tamper with, or use non-public areas of the Sites, Do’s computer systems, or the technical delivery systems of Do’s providers;</p>
			<p>Attempt to probe, scan, or test the vulnerability of any Do system or network or breach any security or authentication measures;</p>
			<p>Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Do or any of Do’s providers or any other third party (including another user) to protect the Sites or Services; or
			Attempt to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Sites or Services.</p>
			<p>User must at all times use the Sites and the Services in a responsible and legal manner. In particular (but not exclusively) User must not do any of the following: misrepresent User’s identity or User’s affiliation with any other person or organization; send junk email or spam to people who do not wish to receive mail from User; delete or falsify any attributions, trademarks or designations of source from any website content; or interfere with or disrupt the service or services or networks connected to the Services or Sites; collect or store personal data about other users including email addresses without consent. User agrees that User will comply with all applicable local, state and federal laws, statutes and regulations regarding use of the Sites and Services.</p>
			<p>Do will investigate and prosecute violations of any of the above to the fullest extent of the law. Do may involve and cooperate with law enforcement authorities in prosecuting Users who violate these Terms of Use.</P>
			<b style="margin-left: 5%;">8. Copyright Policy</b>
			<p>Notice of Copyright Infringement
			Do respects the intellectual property rights of others. Please notify Do in writing, by e-mail or mail to Do’s designated agent listed below, if you believe that a User has infringed your intellectual property rights. Do provides this policy pursuant to Section 512 of the Copyright Revision Act, as enacted through the Digital Millennium Copyright Act (“DMCA”).</p>
			<p>To be effective the notification should include:</p>
			<p>identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works;</p>
			<p>identification of the claimed infringing material and information reasonably sufficient to permit Do to locate the material on the Sites or Services;</p>
			<p>information reasonably sufficient to permit Do to contact you, such as an address, telephone number, and, if available, an e-mail address;</p>
			<p>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</p>
			<p>a statement by you, made under penalty of perjury, that the above information in your notification is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf; and
			your physical or electronic signature.
			You acknowledge and agree that upon receipt and notice of a claim of infringement, Do may immediately remove the identified materials from the Sites and Services without liability.</p>
			<p>Repeat Infringers
			User’s account will be terminated if, in Do’s discretion, User’s determined to be a repeat infringer. Repeat infringers are Users who have been the subject of more than one valid takedown request that has not been successfully rebutted.</p>
			<b style="margin-left: 5%;">9. Pricing</b>
			<p>For information about Do’s pricing, please see Do’s Pricing page. Do reserves the right to change its pricing at any time, with or without notice. Do will post any changes to the Pricing on the Pricing page, so please check often. All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and User shall be responsible for payment of all taxes, levies, or duties associated with User’s purchases hereunder, excluding only United States (federal or state) taxes, if applicable.</p>
			<b style="margin-left: 5%;">10. Dealing with Third Parties.</b>
			<p>The Do Site may provide links to or frame third-party websites or services and may link User automatically to sponsors’ or third party’s websites or services. Do provides such links and framing solely for the convenience of Users. Do does not review or endorse, and are not responsible for, any content, advertising, products, services or other materials on or available from such websites or services. User assumes full responsibility for User’s use of third-party websites or services. User’s interactions with organizations or individuals found on or through the Sites and Services are solely between User and such organizations or individuals. User should make whatever investigation User feels necessary or appropriate before proceeding with any interaction with any of these third parties. User agree that Do is not responsible or liable for any loss or damage of any kind or nature incurred as the result of any such dealings. If there is a dispute between Users, or between Users and any third party, User understands and agrees that Do is under no obligation to become involved. In the event that User has a dispute with any other User, User hereby releases Do and its affiliates, and their officers, employees, agents, and successors from claims, demands, and damages (actual and consequential) of every kind or nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such disputes or the Sites and Services. If USER IS a California resident, USER waiveS California Civil Code Section 1542, which provides: A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.</p>
			<b style="margin-left: 5%;">11. Exclusion of Warranty.</b>
			<p>USER USES THE SITES AND SERVICES AT USER’S OWN RISK. THE SITES, SERVICES, AND THE CONTENTS THEREIN AND/OR THE CONTENT PROVIDED BY Do.COM, ARE PROVIDED “AS IS” AND “AS AVAILABLE”, AND, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ALL WARRANTIES, EXPRESS OR IMPLIED, ARE DISCLAIMED, INCLUDING BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, QUIET ENJOYMENT, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.</p>
			<p>IN PARTICULAR, Do AND ITS OFFICERS, EMPLOYEES, DIRECTORS, SHAREHOLDERS, PARENTS, SUBSIDIARIES, AFFILIATES, AGENTS, AND LICENSORS (REFERRED TO COLLECTIVELY AS “AFFILIATES”) MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT THE ACCURACY OR COMPLETENESS OF CONTENT AVAILABLE ON OR THROUGH THE SITES OR SERVICES (INCLUDING, WITHOUT LIMITATION, any recommendations or other content available on or through the SiteS or Services), OR THE CONTENT OF ANY WEBSITES OR RESOURCES LINKED TO OR FRAMED ON THE SITES OR SERVICES. Do AND ITS AFFILIATES WILL HAVE NO LIABILITY FOR ANY: (a) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (b) PERSONAL INJURY OR PROPERTY DAMAGE RESULTING FROM USER’S ACCESS TO OR USE OF THE SITES OR SERVICES; (c) ANY UNAUTHORIZED ACCESS TO OR USE OF Do’S SERVERS OR OF ANY PERSONAL OR FINANCIAL INFORMATION; (d) ANY INTERRUPTION OF TRANSMISSION TO OR FROM THE SITES OR SERVICES; (e) ANY COMPUTER VIRUSES OR MALICIOUS CODE THAT MAY BE TRANSMITTED ON OR THROUGH THE SITES OR SERVICES; OR (f) ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY FUNCTIONALITY OR CONTENT POSTED, E-MAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE ON OR THROUGH THE SITES OR SERVICES.</p>
			<p>Do AND ITS AFFILIATES DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY THIRD PARTY PRODUCT OR SERVICE RECOMMENDED, ADVERTISED, OR OFFERED ON OR THROUGH THE SITES OR SERVICES OR ANY LINKED OR FRAMED WEBSITE.</p>
			<p>USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR INFORMATION DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SITES OR SERVICES IS DONE AT USER’S OWN RISK AND THAT USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE ARISING FROM DOING SO. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY USER FROM Do OR THROUGH THE SITES OR SERVICES WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE IN THESE TERMS OF USE.</p>
			<b style="margin-left: 5%;">12. Limitation of Liability.</b>
			<p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER Do NOR ITS AFFILIATES WILL BE LIABLE UNDER ANY THEORY OF LIABILITY (WHETHER IN CONTRACT, TORT, NEGLIGENCE, OR OTHERWISE) FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING, DAMAGES FOR LOSS OF REVENUES, PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES (EVEN IF SUCH PARTIES WERE ADVISED OF, KNEW OF, OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES), ARISING FROM OR RELATING TO THE SITES OR SERVICES OR THESE TERMS OF USE.
			Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations and disclaimers may not apply to User. To the extent Do may not, as a matter of applicable law, disclaim any implied warranty or limit its liabilities, the scope and duration of such warranty and the extent of Do’s liability will be the minimum permitted under such law.</p>
			<b style="margin-left: 5%;">13. Indemnification.</b>
			<p>Users are entirely responsible for maintaining the confidentiality of passwords and accounts. Furthermore, Users are entirely responsible for any and all activities that occur under their account. User agrees to indemnify, defend and hold harmless Do and its Affiliates from and against any and all claims, liabilities, damages, losses, costs, expenses, and fees of any kind (including reasonable attorneys’ fees and legal costs), arising from or relating to: (a) any information (including User’s User Content or any other content) that User or anyone using User’s account submits, posts, or transmits on or through the Sites or Services; (b) the use of the Sites or Services by User or anyone using User’s account; (c) the violation of these Terms of Use by User or anyone using User’s account; or (d) the violation of any rights of any third party, including intellectual property, privacy, publicity, or other proprietary rights by User or anyone using User’s account. Do reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by User. If Do does assume the defense of such a matter, User will reasonably cooperate with Do in such defense. User agrees to immediately notify Do of any unauthorized use of User’s account or any other breach of security known to User.</p>
			<b style="margin-left: 5%;">14. International Use.</b>
			<p>The Sites and Services are controlled and operated from within the United States. Do makes no representation that the Sites and Services are appropriate or available in locations outside of the United States. Those who choose to access the Sites or Services from other locations do so at their own risk and are responsible for compliance with applicable laws.</p>
			<b style="margin-left: 5%;">15. Arbitration Agreement & Waiver of Certain Rights</b>
			<p>By accessing or using the Sites or Services, User agrees: (i) that any and all disputes User may have with, or claims User may have against Do relating to, arising out of or connected in any way with (a) the Sites or Services, (b) these Terms of Use, or (c) the determination of the scope or applicability of this agreement to arbitrate (a “Claim”), will be resolved exclusively by final and binding arbitration in accordance with the Rules of the American Arbitration Association (“AAA Rules”). The arbitration will be heard and determined by a single arbitrator. The arbitrator’s decision in any such arbitration will be final and binding upon the parties and may be enforced in any court of competent jurisdiction. The parties agree that the arbitration will be kept confidential and that the existence of the proceeding and any element of it will not be disclosed beyond the arbitration proceedings, except as may be required by applicable law.</p>
			<p> If User demonstrates that the costs of arbitration will be prohibitive as compared to the costs of litigation, Do will pay as much of the administrative costs and arbitrator’s fees required for the arbitration as the arbitrator deems necessary to prevent the cost of the arbitration from being prohibitive. In the final award, the arbitrator may apportion the costs of arbitration and the compensation of the arbitrator among the parties in such amounts as the arbitrator deems appropriate.</p>
			<p>This arbitration agreement does not preclude User from seeking action by federal, state, or local government agencies. User and Do also have the right to bring qualifying claims in small claims court. In addition, User and Do retain the right to apply to any court of competent jurisdiction for provisional relief, including pre-arbitral attachments or preliminary injunctions, and any such request shall not be deemed incompatible with these Terms of Use, nor a waiver of the right to have disputes submitted to arbitration as provided in these Terms of Use.</p>
			<p> Neither User nor Do may act as a class representative or private attorney general, nor participate as a member of a class of claimants, with respect to any Claim. Claims may not be arbitrated on a class or representative basis. The arbitrator can decide only User and/or Do’s individual Claims. The arbitrator may not consolidate or join the claims of other persons or parties who may be similarly situated. If for any reason a claim proceeds in court rather than in arbitration User and Do each waive any right to a jury trial.</p>
			<p>THIS SECTION LIMITS CERTAIN RIGHTS, INCLUDING THE RIGHT TO MAINTAIN A COURT ACTION, THE RIGHT TO A JURY TRIAL, THE RIGHT TO PARTICIPATE IN ANY FORM OF CLASS OR REPRESENTATIVE CLAIM, THE RIGHT TO ENGAGE IN DISCOVERY EXCEPT AS PROVIDED IN THE AAA RULES, AND THE RIGHT TO CERTAIN REMEDIES AND FORMS OF RELIEF. OTHER RIGHTS THAT USER OR Do WOULD HAVE IN COURT ALSO MAY NOT BE AVAILABLE IN ARBITRATION. If any provision of this Section is found to be invalid or unenforceable, then that specific provision shall be of no force and effect and shall be severed, but the remainder of this Section will continue in full force and effect. This Section of these Terms of Use will survive the termination of User’s relationship with Do.</p>
			<b style="margin-left: 5%;">16. Termination.</b>
			<p>Do reserves the right, at its sole discretion, to immediately, with or without notice, suspend or terminate User’s registration, the Terms of Use, and/or User’s access to all or a portion of the Sites or Services and/or remove any registration information or User Content from the Sites or Services, for any reason. Upon termination or expiration of the Terms of Use, User’s obligations and Do’s rights and disclaimers survive, but User’s right to use the Sites and Services immediately ceases.</p>
			<b style="margin-left: 5%;">17. General Provisions.</b>
			<p>These Terms of Use will be governed by and construed in accordance with the laws of the State of California, without reference to its conflicts of laws rules. User agrees that any action of whatever nature arising from or relating to these Terms of Use, the Sites, or any Services will be filed only in the state or federal courts located in San Francisco County, California. User consents and submits to the personal jurisdiction of such courts for the purposes of any such action. Any provision of these Terms of Use that is held to be invalid or unenforceable will be deleted and replaced by a valid and enforceable provision which achieves, as far as possible, the same objectives as the severed provision was intended to achieve. The remaining provisions of these Terms of Use shall continue in full force and effect. Neither these Terms of Use, nor any terms contained herein, shall be construed as creating or constituting a partnership, joint venture or agency relationship between the parties. User may not assign, sublicense or otherwise transfer any right or obligation set forth herein without Do’s prior written consent. Any purported assignment in violation of the preceding sentence is void and of no effect. Do may assign its rights and obligations under these Terms of Use, including in connection with a merger, acquisition, a sale of assets, or by operation of law. Subject to the foregoing, these Terms of Use are binding upon the parties’ respective successors and permitted assigns. No failure of Do to exercise or enforce any of its rights hereunder will act as a waiver of such rights. Except as otherwise expressly provided herein, all remedies provided for herein shall be cumulative and in addition to and not in lieu of any other remedies available to either party at law, in equity or otherwise.</p></p>

			<p style="margin-top: 5%;">© 2018 Do, Inc. All rights reserved.</p></div>
		</div>
	</div>
</center>

<?php }